import os
import json
from typing import Optional


class ReadmeGenerator:
    def __init__(self, workspace_dir: str):
        self.workspace_dir = os.path.abspath(workspace_dir)
        self.output_dir = os.path.join(self.workspace_dir, "output")

    def generate(self) -> Optional[str]:
        if not os.path.isdir(self.output_dir):
            return None

        project_name = os.path.basename(self.workspace_dir)
        files = self._scan_directory(self.output_dir)
        deps = self._detect_dependencies()
        readme = self._build_readme(project_name, files, deps)
        return readme

    def _scan_directory(self, directory: str) -> list:
        result = []
        for root, dirs, files in os.walk(directory):
            dirs[:] = [d for d in dirs if not d.startswith(".") and d not in ("node_modules", "__pycache__", ".venv", "venv")]
            for f in files:
                if f.startswith(".") or f in "task.json":
                    continue
                rel_path = os.path.relpath(os.path.join(root, f), self.output_dir)
                if rel_path == "README.md":
                    continue
                result.append(rel_path)
        result.sort()
        return result

    def _detect_dependencies(self) -> dict:
        info = {"manager": None, "install": "", "run": "", "extra": ""}
        pkg_json = os.path.join(self.output_dir, "package.json")
        req_txt = os.path.join(self.output_dir, "requirements.txt")
        pyproject = os.path.join(self.output_dir, "pyproject.toml")
        cargo = os.path.join(self.output_dir, "Cargo.toml")
        gemfile = os.path.join(self.output_dir, "Gemfile")
        go_mod = os.path.join(self.output_dir, "go.mod")

        if os.path.isfile(pkg_json):
            info["manager"] = "npm"
            info["install"] = "npm install"
            info["run"] = "npm start"
            try:
                with open(pkg_json) as f:
                    data = json.load(f)
                if "scripts" in data:
                    scripts = data["scripts"]
                    if "dev" in scripts:
                        info["run"] = "npm run dev"
                    elif "start" in scripts:
                        info["run"] = "npm start"
                    elif "build" in scripts:
                        info["run"] = "npm run build"
                if "dependencies" in data:
                    info["extra"] = f"Node.js project with {len(data['dependencies'])} dependencies."
            except Exception:
                pass
        elif os.path.isfile(req_txt):
            info["manager"] = "pip"
            info["install"] = "pip install -r requirements.txt"
            info["run"] = "python main.py"
            info["extra"] = "Python project."
        elif os.path.isfile(pyproject):
            info["manager"] = "pip"
            info["install"] = "pip install -e ."
            info["run"] = "python -m your_module"
            info["extra"] = "Python project (pyproject.toml)."
        elif os.path.isfile(cargo):
            info["manager"] = "cargo"
            info["install"] = "cargo build"
            info["run"] = "cargo run"
            info["extra"] = "Rust project."
        elif os.path.isfile(gemfile):
            info["manager"] = "bundler"
            info["install"] = "bundle install"
            info["run"] = "ruby main.rb"
            info["extra"] = "Ruby project."
        elif os.path.isfile(go_mod):
            info["manager"] = "go"
            info["install"] = "go mod download"
            info["run"] = "go run ."
            info["extra"] = "Go project."

        return info

    def _build_readme(self, project_name: str, files: list, deps: dict) -> str:
        lines = []
        lines.append(f"# {project_name}")
        lines.append("")
        lines.append("Project generated by Maria agentic AI.")

        if deps["extra"]:
            lines.append("")
            lines.append(deps["extra"])

        lines.append("")
        lines.append("## Requirements")
        lines.append("")

        if deps["manager"] == "npm":
            lines.append("- Node.js 18+")
            lines.append("- npm")
        elif deps["manager"] == "pip":
            lines.append("- Python 3.9+")
            lines.append("- pip")

        lines.append("")
        lines.append("## Installation")
        lines.append("")
        lines.append("```bash")
        lines.append(deps["install"])
        lines.append("```")

        lines.append("")
        lines.append("## Usage")
        lines.append("")
        lines.append("```bash")
        lines.append(deps["run"])
        lines.append("```")

        if files:
            lines.append("")
            lines.append("## Project Structure")
            lines.append("")
            for f in files:
                lines.append(f"- {f}")

        lines.append("")
        return "\n".join(lines)

    def save_readme(self, readme: str) -> bool:
        readme_path = os.path.join(self.output_dir, "README.md")
        try:
            os.makedirs(self.output_dir, exist_ok=True)
            with open(readme_path, "w", encoding="utf-8") as f:
                f.write(readme)
            return True
        except Exception:
            return False
